# Note: Can't use anything in `.venv` for local hooks when commiting from VSCode GUI.
# This is because VSCode Source Control doesn't activate `.venv` before running `git
# commit`.
#
# Example script to run via "target: pwsh script.ps1"
#
#     & ./.venv/Scripts/Activate.ps1
#     foreach ($arg in $args) {
#         autoflake -i --remove-all-unused-imports --ignore-init-module-imports $arg
#     }
#
# (https://github.com/microsoft/vscode-python/issues/10165)

ci:
  autoupdate_schedule: "quarterly"

repos:
  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.

  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
  - repo: "https://github.com/DavidAnson/markdownlint-cli2"
    rev: "v0.6.0"
    hooks:
      - id: "markdownlint-cli2-fix"
  - repo: "https://github.com/psf/black"
    rev: "23.1.0"
    hooks:
      - id: "black"
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.0.254"
    hooks:
      - id: "ruff"
  - repo: "https://github.com/srstevenson/nb-clean"
    rev: "2.4.0"
    hooks:
      - id: "nb-clean"
        args:
          - "--remove-empty-cells"
          - "--preserve-cell-metadata"
          - "tags"
          - "slideshow"
          - "special"
          - "--"
  - repo: "https://github.com/asottile/blacken-docs"
    rev: "1.13.0"
    hooks:
      - id: "blacken-docs"
        additional_dependencies: ["black==23.1.0"]
  - repo: "https://github.com/nbQA-dev/nbQA"
    rev: "1.6.3"
    hooks:
      - id: "nbqa-black"
        additional_dependencies: ["black==23.1.0"]
      - id: "nbqa-ruff"
        additional_dependencies: ["ruff==0.0.254"]
