name: main

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - run: |
          pip install -U pip setuptools wheel
          pip install -r requirements_lint.txt
          pip install .
      - run: flake8
